[auth]
allowed_redirect_urls = [
  "http://localhost:3000/login",
  "http://localhost:3000/reset-password",
  "http://localhost:3000/dashboard",
  "http://localhost:3000/verify",
  "https://diplomaiq-git-main-iadd.vercel.app/login",
  "https://diplomaiq-git-main-iadd.vercel.app/reset-password",
  "https://diplomaiq-git-main-iadd.vercel.app/dashboard",
  "https://diplomaiq-git-main-iadd.vercel.app/verify"
]
require_email_verification = true
verify_email_method = "code"
reset_password_method = "code"
disable_signup = false

[auth.password]
min_length = 6
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false

[auth.smtp]
enabled = true
host = "smtp.gmail.com"
port = 465
username = "mukeshaitha54@gmail.com"
# password is managed via secrets — run `insforge secrets add SMTP_PASSWORD "<value>"`
password = "env(SMTP_PASSWORD)"
sender_email = "mukeshaitha54@gmail.com"
sender_name = "DocuMind ai"
min_interval_seconds = 60

[storage]
max_file_size_mb = 50

[realtime]
retention_days = 0

[schedules]
retention_days = 7
